### ISSUE TITLE
idk

### ISSUE THREAD

**Issue by zuzu33654** [3eyka/sound-cloudripper#1]
hi , so me and my friends tried using this ripper. but we get some random private links and not from the artist we want . we sent u a friend request in discord to help us

**Comment by 3eyka** [comment]
actually, you can't search for a specific artist, it only bruteforces for any private tracks/sets found.
i am doing a new version of this project in another language, i will add this feature.

**Comment by zuzu33654** [comment]
> actually, you can't search for a specific artist, it only bruteforces for any private tracks/sets found. i am doing a new version of this project in another language, i will add this feature.

my friend and i wanna discus with u on a gc in discord.is it possible?

**Comment by zuzu33654** [comment]
> actually, you can't search for a specific artist, it only bruteforces for any private tracks/sets found. i am doing a new version of this project in another language, i will add this feature.

also my friend is gonna pay u if u help us ripp a link from a specified artist
