### ISSUE TITLE
idk

### ISSUE THREAD

**Issue by zuzu33654** [3eyka/sound-cloudripper#2]
my friend and i wanna discus with u on a gc in discord (we already sent u friend requests). is it possible? also he is gonna pay u if u help us ripp some links from a specified artist

**Comment by 3eyka** [comment]
i don't think you have my discord ?
and as i already told you, i'm just gonna add that feature in my next update.

**Comment by zuzu33654** [comment]
i have your discord , it appears when i open the py file . mine is zuzu/zi.8xs

**Comment by 3eyka** [comment]
actually, this is not my discord lol

**Comment by zuzu33654** [comment]
Sorry for bothering but my friend wants to know when is the new update releasing?

**Comment by zuzu33654** [comment]
so yeah we decided that we will pay u abt 50$ or more if u help us rn
